# Generated by Django 3.2.7 on 2021-09-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmnotes', '0006_alter_observation_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='photo',
        ),
    ]
