# Generated by Django 3.2.7 on 2021-09-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropexplorer', '0002_auto_20210915_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='cover_crop_group',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_scientific_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='family_common_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='family_scientific_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='zone_inclusion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
