# Generated by Django 3.2.7 on 2021-09-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmnotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='is_planted',
        ),
    ]
