# Generated by Django 3.2.7 on 2021-09-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmnotes', '0002_remove_field_is_planted'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_type',
            field=models.CharField(choices=[('weather', 'Weather'), ('crop', 'Crop'), ('soil', 'Soil'), ('water', 'Water'), ('pest', 'Pest'), ('other', 'Other')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
