# Generated by Django 3.2.7 on 2021-09-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmnotes', '0003_observation_observation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='photo',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
