# Generated by Django 5.2.17 on 2026-10-05 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acres', models.FloatField()),
                ('field_type', models.CharField(choices=[('pasture', 'Pasture'), ('cropland', 'Cropland')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('observation_content', models.CharField(max_length=1000)),
                ('observation_type', models.CharField(choices=[('weather', 'Weather'), ('crop', 'Crop'), ('soil', 'Soil'), ('water', 'Water'), ('pest', 'Pest'), ('other', 'Other')], max_length=100)),
                ('observation_date', models.DateField(verbose_name='date observed')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmnotes.field')),
            ],
        ),
    ]
